### PR TITLE
Support b3

### LINKED ISSUE #79: add support for b3
Add the ability to configure b3 support.  It's currently hardcoded to trace_context.

### PR DESCRIPTION
**Pull request by rnburn**
Fixes #79 

Need for integration with Ambassador

### CODE REVIEW

**Comment by rnburn** [comment]
@davexroth

**Review by jcchavezs — APPROVED** [review]
LGTM

**Comment by jcchavezs** [comment]
Great work @rnburn. Do you mind adding the counter part for census? https://github.com/hypertrace/goagent/blob/main/instrumentation/opencensus/init.go

**Comment by jcchavezs** [comment]
Related https://github.com/hypertrace/goagent/pull/61

**Comment by rnburn** [comment]
@jcchavezs - Does anything need to be done for census?

My understanding is that you explicitly specify a propagation format whenever you extract or inject the context (like shown here https://github.com/hypertrace/goagent/blob/main/instrumentation/opencensus/net/hyperhttp/transport_test.go#L184). 

I don't believe there's any global config equivalent for what opentelemetry has.

**Pull request merged**
